version: "3.1"
services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8000:80"
  #     - "443"
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
  #     - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
  #   links:
  #     - app

  app_dev:
    image: node:14
    build: .
    container_name: sommelier_app_dev
    links:
      - redis_dev
    ports:
      - "4000:4000"
    env_file: ./.env
    environment:
      - PORT=4000
      - REDIS_URL=cache_dev

  redis_dev:
    image: redis:alpine
    container_name: cache_dev
    command: ["redis-server", "--bind", "redis", "--port", "6380"]
    ports:
      - "6380:6380"