version: "3.1"
services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8000:80"
  #     - "443"
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
  #     - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
  #   links:
  #     - app

  app:
    image: node:14
    build: .
    container_name: sommelier-app
    depends_on:
      - redis
    ports:
      - "4000:4000"
    env_file: ./.env
    environment:
      - PORT=4000
      - REDIS_URL=redis://cache

  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - "6379:6379"