version: "3.1"
services:
  somm_app:
    image: somm_app
    build: .
    container_name: somm_app
    # Run with datadog agent
    # entrypoint: ["/app/entrypoint.sh"]
    command: ["pm2-runtime", "packages/server/dist/index.js"]
    links:
      - redis_app
    ports:
      - "4000:4000"
    env_file: ./.env
    environment:
      - PORT=4000
      - REDIS_URL=redis_app
      - REDIS_PORT=6380

  somm_worker:
    image: somm_app
    build: .
    container_name: somm_worker
    # Run with datadog agent
    # entrypoint: ["/app/worker-entrypoint.sh"]
    command: ["pm2-runtime", "packages/workers/dist/scheduler.js"]
    links:
      - redis_app
    env_file: ./.env
    environment:
      - REDIS_URL=redis_app
      - REDIS_PORT=6380
      - WORKER_CACHE_WARMER=true
      - WORKER_CACHE_WARMER_CRON="*/5 * * * *"

  redis_app:
    image: redis:alpine
    container_name: redis_app
    command: ["redis-server", "--bind", "redis_app", "--port", "6380"]
    ports:
      - "6380:6380"