version: "3.1"
services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8000:80"
  #     - "443"
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
  #     - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
  #   links:
  #     - app

  app:
    image: node:14
    build: .
    container_name: sommelier_app
    links:
      - redis
    ports:
      - "3001:3001"
    env_file: ./.env
    environment:
      - REDIS_URL=cache

  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - "6379:6379"